export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const YEAR_SAVED = 'YEAR_SAVED';
export const YEAR_FETCHED = 'YEAR_FETCHED';
export const YEAR_UPDATED = 'YEAR_UPDATED';
export const YEAR_DELETED = 'YEAR_DELETED';